### PR TITLE
Fix IOS 8 ContentSize issue

### PR DESCRIPTION
**Pull request by dErangaPrasad**
PopOver not working correctly in IOS 8

### CODE REVIEW

**Comment by skywinder** [comment]
@dErangaPrasad  Thank you! :+1:

**Comment by skywinder** [comment]
@dErangaPrasad  Oh. It's old repo. Because I remember, that already fix it before! Please, Use https://github.com/skywinder/ActionSheetPicker-3.0

**Comment by dErangaPrasad** [comment]
@skywinder I didn't see that version 3.0
Sorry for that :)

**Review by avendanoirvin — COMMENTED** [review]
> `[avendanoirv956@gmail.com]() `

**Pull request merged**
